#!/bin/sh
set -eu

umask 077

root_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root_dir"

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  printf '%s\n' \
    'Usage: ./scripts/install.sh' \
    '' \
    'Interactively configure and deploy a new production Owl Memory instance.' \
    'The installer refuses to replace an existing .env file.'
  exit 0
fi

cleanup() {
  stty echo 2>/dev/null || true
}
trap cleanup EXIT INT TERM

fail() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

prompt() {
  label=$1
  default=${2:-}
  if [ -n "$default" ]; then
    printf '%s [%s]: ' "$label" "$default" >&2
  else
    printf '%s: ' "$label" >&2
  fi
  IFS= read -r answer
  if [ -z "$answer" ]; then
    answer=$default
  fi
  printf '%s' "$answer"
}

prompt_secret() {
  label=$1
  printf '%s: ' "$label" >&2
  stty -echo
  IFS= read -r answer
  stty echo
  printf '\n' >&2
  printf '%s' "$answer"
}

reject_apostrophe() {
  label=$1
  value=$2
  case "$value" in
    *"'"*) fail "$label cannot contain an apostrophe" ;;
  esac
}

command -v docker >/dev/null 2>&1 || fail "Docker is required"
command -v openssl >/dev/null 2>&1 || fail "OpenSSL is required"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required"
docker info >/dev/null 2>&1 || fail "The Docker daemon is not available"
[ -t 0 ] || fail "Run this installer in an interactive terminal"
[ ! -e .env ] || fail ".env already exists; use ./scripts/deploy.sh to update this instance"

printf 'Owl Memory production setup\n\n'

domain=$(prompt "Public domain, without https://" "")
case "$domain" in
  ""|*://*|*/*|*:*|*" "*) fail "Enter a hostname such as memory.example.com" ;;
esac
printf '%s' "$domain" \
  | grep -Eq '^([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$' \
  || fail "Enter a valid fully qualified domain name"

owner_email=$(prompt "Owner email" "")
printf '%s' "$owner_email" | grep -Eq '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' \
  || fail "Enter a valid owner email"
owner_name=$(prompt "Owner display name" "Owner")

llm_base_url=$(prompt "OpenAI-compatible API base URL" "https://api.openai.com/v1")
case "$llm_base_url" in
  http://*|https://*) ;;
  *) fail "The API base URL must start with http:// or https://" ;;
esac
llm_model=$(prompt "Model name" "")
[ -n "$llm_model" ] || fail "A model name is required"
llm_api_key=$(prompt_secret "API key (leave empty for a keyless local provider)")

allow_signup=$(prompt "Allow public account registration? (yes/no)" "no")
case "$allow_signup" in
  yes|y) allow_signup=true ;;
  no|n) allow_signup=false ;;
  *) fail "Answer yes or no for public registration" ;;
esac

resend_api_key=""
mail_from=""
if [ "$allow_signup" = true ]; then
  resend_api_key=$(prompt_secret "Resend API key")
  [ -n "$resend_api_key" ] || fail "Public registration requires a Resend API key"
  mail_from=$(prompt "Verified sender, for example Owl Memory <owl@example.com>" "")
  [ -n "$mail_from" ] || fail "Public registration requires a verified sender"
fi

owner_password=$(prompt_secret "Owner password (12 characters minimum)")
[ "${#owner_password}" -ge 12 ] || fail "The owner password must contain at least 12 characters"
owner_password_again=$(prompt_secret "Repeat owner password")
[ "$owner_password" = "$owner_password_again" ] || fail "The passwords do not match"

reject_apostrophe "Domain" "$domain"
reject_apostrophe "Owner display name" "$owner_name"
reject_apostrophe "LLM base URL" "$llm_base_url"
reject_apostrophe "Model name" "$llm_model"
reject_apostrophe "LLM API key" "$llm_api_key"
reject_apostrophe "Resend API key" "$resend_api_key"
reject_apostrophe "Mail sender" "$mail_from"

printf '\nGenerating instance secrets...\n'
postgres_password=$(openssl rand -hex 32)
postgres_super_password=$(openssl rand -hex 32)
master_key=$(openssl rand -base64 32)
cookie_keys="$(openssl rand -base64 32),$(openssl rand -base64 32)"
jwt_jwks=$(
  docker run --rm --network none -i \
    node:24-alpine node --input-type=module - \
    < deploy/setup/generate-jwks.mjs
)
case "$jwt_jwks" in
  '{"keys":['*) ;;
  *) fail "Could not generate the OAuth signing key" ;;
esac

cat > .env <<EOF
# Generated by scripts/install.sh. Keep this file private and escrow OWL_MASTER_KEY.
NODE_ENV='production'
OWL_PUBLIC_URL='https://$domain'
OWL_DATABASE_URL='postgres://owl_app:$postgres_password@postgres:5432/owl'
OWL_DATABASE_ADMIN_URL='postgres://postgres:$postgres_super_password@postgres:5432/owl'
OWL_POSTGRES_PASSWORD='$postgres_password'
OWL_POSTGRES_SUPER_PASSWORD='$postgres_super_password'
OWL_POSTGRES_PORT='55432'

OWL_MASTER_KEY='$master_key'
OWL_COOKIE_KEYS='$cookie_keys'
OWL_JWT_JWKS='$jwt_jwks'

OWL_BLOB_DIR='/data/blobs'
OWL_EXPORT_DIR='/data/exports'
OWL_ALLOW_SIGNUP='$allow_signup'
OWL_DEV_AUTH='false'
OWL_LOG_LEVEL='info'
OWL_EMBEDDINGS_URL='http://embeddings:8790'
OWL_EMBEDDING_MODEL='intfloat/multilingual-e5-small'

OWL_LLM_ENABLED='true'
OWL_LLM_BASE_URL='$llm_base_url'
OWL_LLM_MODEL='$llm_model'
OWL_LLM_API_KEY='$llm_api_key'
OWL_LLM_REASONING_EFFORT=''
OWL_LLM_TIMEOUT_MS='45000'
OWL_LLM_MAX_INPUT_CHARS='24000'
OWL_LLM_CONCURRENCY='4'

OWL_RESEND_API_KEY='$resend_api_key'
OWL_MAIL_FROM='$mail_from'

OWL_BACKUP_HOST_DIR='./backups'
OWL_BACKUP_AGE_RECIPIENT=''
OWL_DOMAIN='$domain'
EOF
chmod 600 .env
mkdir -p backups
chmod 700 backups

unset owner_password_again llm_api_key resend_api_key

printf 'Building and starting Owl Memory...\n'
./scripts/deploy.sh

printf 'Creating the first owner...\n'
printf '%s\n' "$owner_password" \
  | docker compose \
    -f docker-compose.yml \
    -f compose.production.yml \
    run --rm --no-deps -T \
    api node apps/api/dist/admin.js -- create-owner \
    --email "$owner_email" \
    --name "$owner_name" \
    --password-file /dev/stdin
unset owner_password

printf '\nOwl Memory is running at https://%s\n' "$domain"
printf 'Store .env in an encrypted secrets manager before adding knowledge.\n'
